version: '3'

services:
  test-backend:
    build: ./back
    ports:
      - "7000:7000"
    depends_on:
      - test-db

  test-db:
    build: ./postgres
    ports: 
      - "5432:5432"

  frontend-test:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - "test-backend"