version: '3'

services:
  test-backend:
    build: ./back
    ports:
      - "7000:7000"

  # postgres-db:
  #   image: postgres:9.4.11-alpine
  #   volumes:
  #     - ./dbScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     POSTGRES_PASSWORD: dbpass
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: test
  #   ports:
  #     - 5437:5437